export const FETCH_WORKERS = 'FETCH_WORKERS';

export const FETCH_WORKER_DETAILS = 'FETCH_WORKER_DETAILS';
export const EDIT_WORKER_DETAILS = 'EDIT_WORKER_DETAILS';

export const ADD_WORKER = 'ADD_WORKER'